name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Specify your Node.js version here

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      # Install dependencies and build
      - name: Install and Build
        run: |
          npm install
          npm run p-build-all

      # Compress each folder in /build/dist
      - name: Compress Executables
        run: |
          mkdir -p compressed
          for folder in $(ls build/dist); do
            tar -czvf "compressed/${folder}.tar.gz" -C "build/dist/${folder}" .
          done

      # Create a new release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload compressed files to the release
      - name: Upload Release Assets
        run: |
          for file in compressed/*; do
            echo "Uploading $file"
            gh release upload ${{ steps.create_release.outputs.upload_url }} $file
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
