name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]  # Set your Node.js version here
        go-version: [1.21]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: npm install

    - name: Build the app
      env:
        CI: false
      run: npm run build

    - name: Upload executables
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: |
          build/dist/**
        retention-days: 1

  test:
    name: Test
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64
          # - os: windows-latest
          #   arch: x64
          # - os: macos-latest
          #   arch: x64
          # - os: macos-latest
          #   arch: arm64
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker (Linux)
      if: matrix.os == 'linux-latest'
      uses: docker/setup-buildx-action@v1

    # - name: Set up Docker (Windows)
    #   if: matrix.os == 'windows-latest'
    #   run: |
    #     choco install docker-desktop -y

    # - name: Setup Docker (macOS)
    #   if: matrix.os == 'macos-latest'
    #   uses: douglascamata/setup-docker-macos-action@v1-alpha

    # - name: Start Docker (Windows)
    #   if: matrix.os == 'windows-latest'
    #   run: |
    #     # Start Docker daemon
    #     # Implement a retry/wait mechanism if necessary


    - name: Download executables
      uses: actions/download-artifact@v3
      with:
        name: executables
        path: build/dist

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Mocha tests
      run: npm run test-executables